# Generated by Django 3.2.25 on 2025-08-14 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20250813_0717'),
    ]

    operations = [
        # Add new rental pricing fields to Product model
        migrations.AddField(
            model_name='product',
            name='rental_price_3months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_6months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_12months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price_24months',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='student_discount_percentage',
            field=models.IntegerField(default=10, help_text='Student discount in percentage'),
        ),
        migrations.AddField(
            model_name='product',
            name='basic_insurance_monthly',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='premium_insurance_monthly',
            field=models.DecimalField(decimal_places=2, default=14.99, max_digits=6),
        ),
        
        # Create RentalOrder model
        migrations.CreateModel(
            name='RentalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('rental_duration', models.IntegerField(choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months'), (24, '24 Months')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('student_discount_applied', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('insurance_type', models.CharField(choices=[('none', 'No Insurance'), ('basic', 'Basic Insurance'), ('premium', 'Premium Insurance')], default='none', max_length=20)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('includes_lessons', models.BooleanField(default=True)),
                ('lesson_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='auth.User')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
